<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.0 setup script
 * Date: Sun, 08 Apr 2012 14:35:10 +0800
 */

/* Servers configuration */
$i = 0;

/* Server: My Local MySQL server [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'My Local MySQL server';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['compress'] = true;
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][$i]['controluser'] = 'phpmyadmin';
$cfg['Servers'][$i]['controlpass'] = 'phpmyadmin';
$cfg['Servers'][$i]['bookmarktable'] = 'pma_bookmark';
$cfg['Servers'][$i]['relation'] = 'pma_relation';
$cfg['Servers'][$i]['table_info'] = 'pma_table_info';
$cfg['Servers'][$i]['table_coords'] = 'pma_table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma_pdf_pages';
$cfg['Servers'][$i]['column_info'] = 'pma_column_info';
$cfg['Servers'][$i]['history'] = 'pma_history';
$cfg['Servers'][$i]['designer_coords'] = 'pma_designer_coords';
$cfg['Servers'][$i]['userconfig'] = 'pma_userconfig';
$cfg['Servers'][$i]['recent'] = 'pma_recent';
$cfg['Servers'][$i]['table_uiprefs'] = 'pma_table_uiprefs';
$cfg['Servers'][$i]['tracking'] = 'pma_tracking';
$cfg['Servers'][$i]['MaxTableUiprefs'] = 1000;
$cfg['Servers'][$i]['tracking_version_auto_create'] = true;

/* End of servers configuration */

$cfg['DefaultLang'] = 'zh_CN';
$cfg['ThemeDefault'] = 'original';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['AjaxEnable'] = false;
$cfg['ServerDefault'] = 1;
$cfg['QueryHistoryDB'] = true;
$cfg['MaxCharactersInDisplayedSQL'] = 5000;
$cfg['LeftFrameDBTree'] = false;
$cfg['PersistentConnections'] = true;
$cfg['ExecTimeLimit'] = 0;
$cfg['PropertiesIconic'] = true;
$cfg['ShowPhpInfo'] = true;
$cfg['blowfish_secret'] = 'fsctoken';


/* Addition config */
include('./config_patch.inc.php');

?>
